config/routes.rb
Rails.application.routes.draw do
	devise_for :users	
	root 'uploads#new'
	resources :uploads, only: [:new, :create, :index]
	get 'view_users', to: 'uploads#index', as: :view_users

end
	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Devise modules
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
end

app/controllers/application_controller.rb
# app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def create
    excel_file = params[:file]
    if excel_file.present?
      result = process_excel_file(excel_file)
      flash[:notice] = "Total users: #{result[:total_rows]}, Successful: #{result[:successful]}, Failed: #{result[:failed]}"
      flash[:failure_reasons] = result[:errors]

    else
      flash[:alert] = "Please select an Excel file."
    end
    redirect_to new_upload_path
  end


  private

  def process_excel_file(file)
    result = { total_rows: 0, successful: 0, failed: 0, errors: [] }
    spreadsheet = Roo::Excelx.new(file.path)

    header_mapping = { 'FIRST_NAME' => 'first_name', 'LAST_NAME' => 'last_name', 'EMAIL_ID' => 'email' }

    # Create a hash with header names as keys
    headers = spreadsheet.row(1).map { |header| header&.to_s&.strip }

    spreadsheet.each_row_streaming(header_search: headers) do |row|
      result[:total_rows] += 1
      attributes = {}

      headers.each_with_index do |header, i|
        source_header = header_mapping[header]
        cell_value = row[i].to_s.strip
        attributes[source_header.to_sym] = cell_value
      end

      # Generate a random password and password confirmation
      generated_password = Devise.friendly_token.first(8)
      attributes[:password] = generated_password
      attributes[:password_confirmation] = generated_password

      user = User.new(attributes)

      if user.save
        result[:successful] += 1
      else
        result[:failed] += 1
        result[:errors] << "Row #{result[:total_rows]}: #{user.errors.full_messages.to_sentence}"
      end
    end

    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Excel</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

	<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
	<%= javascript_importmap_tags %>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container">
			<a class="navbar-brand" href="/">Your App Name</a>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav ml-auto">
					<% if user_signed_in? %>
					<li class="nav-item">
						<%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
					</li>
					<% else %>
					<li class="nav-item">
						<%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
					</li>
					<li class="nav-item">
						<%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
	<%= yield %>
</body>
</html>

app/views/uploads/create.html.erb
<h1>Create a new item</h1>

app/views/uploads/index.html.erb
<h1>List of Users</h1>
<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/uploads/new.html.erb
<h1>New Item</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <%= form_with(url: uploads_path, local: true, multipart: true, html: { class: 'form' }) do |form| %>
          <div class="form-group">
            <%= form.label :file %>
            <%= form.file_field :file, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= form.submit "Upload and Process", class: 'btn btn-primary' %>
            <%= link_to "View Users", uploads_path, class: "btn btn-primary" %>

          </div>
          <% end %>
          
          <% if flash[:notice].present? %>
          <div class="alert alert-success">
            <p><%= flash[:notice] %></p>
          </div>
          <% end %>

          <% if flash[:alert].present? %>
          <div class="alert alert-danger">
            <p><%= flash[:alert] %></p>
          </div>
          <% end %>

          <% if flash[:failure_reasons].present? %>
          <div class="alert alert-warning">
            <h3>Failure Reasons:</h3>
            <ul>
              <% flash[:failure_reasons].each do |reason| %>
              <li><%= reason %></li>
              <% end %>
            </ul>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>